services:
  user_db:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      mec_network:
      #     ipv4_address: 172.28.0.2
  user_sys:
    env_file: .env
    build: .
    command: npm run start:debug
    volumes:
      - .:/code
    ports:
      - '${API_PORT}:${API_PORT}'
      - '9229:9229'
    networks:
      - mec_network
    environment:
      - ENCRYPTION_KEY=wpkHKy+YMmNiyhCRFY6d7vu/ntio7A4J+bGEvrtMLPk=

networks:
  mec_network:
    driver: bridge
    ipam:
      driver: default
