import { PaginatedResponseDto } from '@/baseDto/pagination.dto';
import { ToArray } from '@/commonDecorators/array.decorator';
import { GetDepartmentDto } from '@/departmentDto/department.dto';
import { EXAMPLE_USER_ID } from '@/userConst/user.const';
import { GetUserDto } from '@/userDto/user.dto';
import { ApiProperty } from '@nestjs/swagger';

import { Type } from 'class-transformer';
import { IsDate, IsNotEmpty, IsUUID, ValidateNested } from 'class-validator';
import { UUID } from 'crypto';

export class AssignDepartmentsDto {
  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'List of departments IDs to assign to the user',
  })
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  departmentIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs to which departments will be assigned',
  })
  @IsUUID(4)
  @IsNotEmpty()
  userId: UUID;

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs by whom assigned departments to user',
  })
  @IsUUID(4)
  @IsNotEmpty()
  assignedBy: UUID;

  constructor(departmentIds: UUID[], userId: UUID, assignedBy: UUID) {
    this.departmentIds = departmentIds;
    this.userId = userId;
    this.assignedBy = assignedBy;
  }
}

export class UnAssignDepartmentsDto {
  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'List of departments IDs to assign to the user',
  })
  @ToArray()
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  departmentIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'User IDs to which departments will be assigned',
  })
  @ToArray()
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  userIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs by whom assigned departments to user',
  })
  @IsUUID(4)
  @IsNotEmpty()
  assignedBy: UUID;

  constructor(departmentIds: UUID[], userIds: UUID[], assignedBy: UUID) {
    this.departmentIds = departmentIds;
    this.userIds = userIds;
    this.assignedBy = assignedBy;
  }
}

/**
 * Complete user department data DTO for API responses including system-generated fields.
 */
export class UserDepartmentResponseDto {
  @ApiProperty({
    description: 'Unique user identifier generated by the system',
    example: EXAMPLE_USER_ID,
    format: 'uuid',
    type: String,
    readOnly: true,
  })
  @IsUUID()
  id: UUID;

  @ApiProperty({
    title: 'Department',
    description: 'Department assigned to the user',
    type: GetDepartmentDto,
    isArray: true,
  })
  @Type(() => GetDepartmentDto)
  @ValidateNested()
  departments: GetDepartmentDto;

  @ApiProperty({
    title: 'User',
    description: 'User assigned to the department',
    type: () => GetUserDto,
    isArray: true,
  })
  @Type(() => GetUserDto)
  @ValidateNested()
  users: GetUserDto;

  @ApiProperty({
    title: 'Assigned By User',
    description: 'Details of the user who assigned this department',
    example: EXAMPLE_USER_ID,
    format: 'uuid',
    type: () => GetUserDto,
    required: true,
  })
  @Type(() => GetUserDto)
  @ValidateNested()
  assignedBy: GetUserDto;

  @ApiProperty({
    description: 'Date when the user was assigned to department',
    example: '2023-01-01T12:00:00.000Z',
    format: 'date-time',
    type: Date,
  })
  @IsDate()
  createdAt: Date;

  constructor(
    id: UUID,
    assignedBy: GetUserDto,
    createdAt: Date,
    departments: GetDepartmentDto,
    users: GetUserDto,
  ) {
    this.id = id;
    this.assignedBy = assignedBy;
    this.departments = departments;
    this.users = users;
    this.createdAt = createdAt;
  }
}

export class UserDepartmentListResponseDto extends PaginatedResponseDto {
  @ApiProperty({
    description: 'Array of user objects matching the query criteria',
    type: UserDepartmentResponseDto,
    isArray: true,
  })
  @Type(() => UserDepartmentResponseDto)
  @ValidateNested({ each: true })
  userDepartments: UserDepartmentResponseDto[];

  constructor(
    total: number,
    page: number,
    limit: number,
    totalPages: number,
    userDepartments: UserDepartmentResponseDto[],
  ) {
    super(total, page, limit, totalPages);
    this.userDepartments = userDepartments;
  }
}
