import { ToArray } from '@/common/decorators/array.decorator';
import { DepartmentResponseDto } from '@/department/dto/department.dto';
import { EXAMPLE_USER_ID } from '@/lib/const/user.const';
import { GetUserDto } from '@/user/dto/user.dto';
import { ApiProperty } from '@nestjs/swagger';

import { Type } from 'class-transformer';
import { IsDate, IsNotEmpty, IsUUID, ValidateNested } from 'class-validator';
import { UUID } from 'crypto';

export class AssignDepartmentsDto {
  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'List of departments IDs to assign to the user',
  })
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  departmentIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs to which departments will be assigned',
  })
  @IsUUID(4)
  @IsNotEmpty()
  userId: UUID;

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs by whom assigned departments to user',
  })
  @IsUUID(4)
  @IsNotEmpty()
  assignedBy: UUID;

  constructor(departmentIds: UUID[], userId: UUID, assignedBy: UUID) {
    this.departmentIds = departmentIds;
    this.userId = userId;
    this.assignedBy = assignedBy;
  }
}

export class UnAssignDepartmentsDto {
  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'List of departments IDs to assign to the user',
  })
  @ToArray()
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  departmentIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'User IDs to which departments will be assigned',
  })
  @ToArray()
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  userIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs by whom assigned departments to user',
  })
  @IsUUID(4)
  @IsNotEmpty()
  assignedBy: UUID;

  constructor(departmentIds: UUID[], userIds: UUID[], assignedBy: UUID) {
    this.departmentIds = departmentIds;
    this.userIds = userIds;
    this.assignedBy = assignedBy;
  }
}

/**
 * Complete user department data DTO for API responses including system-generated fields.
 */
export class UserDepartmentResponseDto {
  @ApiProperty({
    description: 'Unique user identifier generated by the system',
    example: EXAMPLE_USER_ID,
    format: 'uuid',
    type: String,
    readOnly: true,
  })
  @IsUUID()
  id: UUID;

  @ApiProperty({
    title: 'Department',
    description: 'List of departments assigned to the user',
    type: DepartmentResponseDto,
    isArray: true,
  })
  @Type(() => DepartmentResponseDto)
  @ValidateNested()
  department: DepartmentResponseDto;

  @ApiProperty({
    title: 'Assigned By User',
    description: 'Details of the user who assigned this department',
    example: EXAMPLE_USER_ID,
    format: 'uuid',
    type: () => GetUserDto,
    required: true,
  })
  @Type(() => GetUserDto)
  @ValidateNested()
  assignedBy: GetUserDto;

  @ApiProperty({
    description: 'Date when the user was assigned to department',
    example: '2023-01-01T12:00:00.000Z',
    format: 'date-time',
    type: Date,
  })
  @IsDate()
  createdAt: Date;

  constructor(
    id: UUID,
    assignedBy: GetUserDto,
    createdAt: Date,
    department: DepartmentResponseDto,
  ) {
    this.id = id;
    this.assignedBy = assignedBy;
    this.department = department;
    this.createdAt = createdAt;
  }
}
