import { PaginatedResponseDto } from '@/baseDto/pagination.dto';
import { ToArray } from '@/commonDecorators/array.decorator';
import { GetRoleResponseDto } from '@/roleDto/role.dto';
import { EXAMPLE_USER_ID } from '@/userConst/user.const';
import { GetUserDto } from '@/userDto/user.dto';
import { ApiProperty } from '@nestjs/swagger';

import { Type } from 'class-transformer';
import { IsDate, IsNotEmpty, IsUUID, ValidateNested } from 'class-validator';
import { UUID } from 'crypto';

export class AssignRolesDto {
  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'List of role IDs to assign to the user',
  })
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  roleIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs to which role will be assigned',
  })
  @IsUUID(4)
  @IsNotEmpty()
  userId: UUID;

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs to who assigned roles to user',
  })
  @IsUUID(4)
  @IsNotEmpty()
  assignedBy: UUID;

  constructor(roleIds: UUID[], userId: UUID, assignedBy: UUID) {
    this.roleIds = roleIds;
    this.userId = userId;
    this.assignedBy = assignedBy;
  }
}

export class UnAssignRolesDto {
  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'List of role IDs to assign to the user',
  })
  @ToArray()
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  roleIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: true,
    description: 'User IDs to which role will be assigned',
  })
  @ToArray()
  @IsUUID(4, { each: true })
  @IsNotEmpty()
  userIds: UUID[];

  @ApiProperty({
    type: String,
    format: 'uuid',
    isArray: false,
    description: 'User IDs to who assigned roles to user',
  })
  @IsUUID(4)
  @IsNotEmpty()
  assignedBy: UUID;

  constructor(roleIds: UUID[], userIds: UUID[], assignedBy: UUID) {
    this.roleIds = roleIds;
    this.userIds = userIds;
    this.assignedBy = assignedBy;
  }
}

/**
 * Complete user role data DTO for API responses including system-generated fields.
 * Extends UserRoleBaseDto with read-only fields like ID, account status, and security tokens
 */
export class UserRoleResponseDto {
  @ApiProperty({
    description: 'Unique user identifier generated by the system',
    example: EXAMPLE_USER_ID,
    format: 'uuid',
    type: String,
    readOnly: true,
  })
  @IsUUID()
  id: UUID;

  @ApiProperty({
    title: 'Roles',
    description: 'List of roles assigned to the user',
    type: GetRoleResponseDto,
    isArray: true,
  })
  @Type(() => GetRoleResponseDto)
  @ValidateNested()
  roles: GetRoleResponseDto;

  @ApiProperty({
    title: 'Assigned By User',
    description: 'Details of the user who assigned this role',
    example: EXAMPLE_USER_ID,
    format: 'uuid',
    type: () => GetUserDto,
    required: true,
  })
  @Type(() => GetUserDto)
  @ValidateNested()
  assignedBy: GetUserDto;

  @ApiProperty({
    title: 'User',
    description: 'User assigned to the department',
    type: () => GetUserDto,
    isArray: true,
  })
  @Type(() => GetUserDto)
  @ValidateNested()
  users: GetUserDto;

  @ApiProperty({
    description: 'Date when the user account was created',
    example: '2023-01-01T12:00:00.000Z',
    format: 'date-time',
    type: Date,
  })
  @IsDate()
  createdAt: Date;

  @ApiProperty({
    description: 'Date when the user account was last updated',
    example: '2023-01-02T12:00:00.000Z',
    format: 'date-time',
    type: Date,
  })
  @IsDate()
  updatedAt: Date;

  constructor(
    id: UUID,
    assignedBy: GetUserDto,
    createdAt: Date,
    updatedAt: Date,
    roles: GetRoleResponseDto,
    users: GetUserDto,
  ) {
    this.id = id;
    this.assignedBy = assignedBy;
    this.roles = roles;
    this.users = users;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}

/**
 * Paginated response wrapper for user list endpoints.
 * Extends base pagination with strongly-typed user array validation.
 */
export class UserRoleListResponseDto extends PaginatedResponseDto {
  @ApiProperty({
    description: 'Array of user objects matching the query criteria',
    type: UserRoleResponseDto,
    isArray: true,
  })
  @Type(() => UserRoleResponseDto)
  @ValidateNested({ each: true })
  userRoles: UserRoleResponseDto[];

  constructor(
    total: number,
    page: number,
    limit: number,
    totalPages: number,
    userRoles: UserRoleResponseDto[],
  ) {
    super(total, page, limit, totalPages);
    this.userRoles = userRoles;
  }
}
